name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Volta
        uses: volta-cli/action@v4
        with:
          node-version: 20.10.0
          npm-version: 10.2.3

      - name: Install
        shell: bash
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

  build:

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.10.0]
        npm-version: [10.2.3]
        os: [windows-latest, ubuntu-latest]

    name: Build (${{ matrix.os }}, 'node ${{ matrix.node-version }}', 'npm ${{ matrix.npm-version }}')
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Volta
        uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        shell: bash
        run: |
          npm ci

      - name: Build
        shell: bash
        run: |
          npm run build

      - name: Test
        shell: bash
        run: |
          npm run test

